[workspace]
members = [".", "common", "compiler", "jit", "runner", "runtime"]
resolver = "3"

[workspace.package]
edition = "2024"
repository = "https://github.com/Ismaxis/trombone-lang"

[workspace.dependencies]
trombone-common = { path = "./common" }
trombone-runtime = { path = "./runtime" }
trombone-compiler = { path = "./compiler" }
trombone-jit = { path = "./jit" }
trombone-runner = { path = "./runner" }
