[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
repository = "https://github.com/Ismaxis/trombone-lang"

[workspace.dependencies]
trombone-common = { path = "./crates/common" }
trombone-runtime = { path = "./crates/runtime" }
trombone-jit = { path = "./crates/jit" }
trombone-runner = { path = "./crates/runner" }
trombone-compiler = { path = "./crates/compiler" }
