on: push

name: main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  test-runtime:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker testing
        uses: ./docker/runtime/
  test-compiler:
    needs: format
    runs-on: ubuntu-latest
    container:
      image: mishasychev/trombone:latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Debug
        run: |
          make -C compiler build
          make -C compiler test
      - name: Test Release
        run: |
          make -C compiler build PRESET=release
          make -C compiler test PRESET=release
